# Generated by Django 4.1.4 on 2023-08-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(max_length=140, verbose_name="ツイート内容"),
        ),
    ]
